### ISSUE TITLE
Top slot in Mailbox not retaining destination still.

### ISSUE THREAD

**Issue by keenerb** [shadowmage45/AncientWarfare#3]
Latest .34 build of AW, top slot continually resets to no destination.

**Comment by shadowmage45** [comment]
I was pretty sure I had this fixed (at least it worked fine during testing of loading/saving/reloading worlds).  I will give this another good look over for one of the next updates.  Thanks for letting me know there are still issues with it.

**Comment by shadowmage45** [comment]
I'm checking in my dev code right now and cannot reproduce this issue using a basic setup.  Is there a particular setup/layout of your mailboxes/locations that might be contributing to the issue? (mailboxes in other dimensions/etc) -- just looking for more information on where to even start looking for the bug.  

With two mailboxes (A & B) placed several blocks apart, setting A's output boxes to B, and B's output boxes to A -- I can load/save, exit completely, reload, etc, with no issues.  (There was indeed a problem in the .033 and earlier releases, but should have been fixed in the .034 release).

Will leave this open for now, but closing soon if I cannot reproduce the issue.

**Comment by keenerb** [comment]
SMP, separate dimensions.  All other slots retain destinations.  It seems to happen after a server restart.

**Comment by shadowmage45** [comment]
Thanks, I'll take a further look into the SMP aspect of it then, see if I can duplicate it that way -- sounds like it is probably a simple NBT data problem.

**Comment by keenerb** [comment]
Wrong server version of AW mod.  Not an issue.
