### ISSUE TITLE
Vehicle icons are purple/black squares when "use vehicle models" is set to false

### ISSUE THREAD

**Issue by keenerb** [shadowmage45/AncientWarfare#31]
http://i.imgur.com/0ghcBKA.png

0.36

**Comment by shadowmage45** [comment]
Yah...this is caused by....surprise!! there are no icons for vehicles!!  At one point, I had a few hold-over icons from the original CatapultMod -- but they were quite terrible looking, and only available for a small selection of vehicles.

I will probably be removing this config toggle...unless someone volunteers to make a bunch of vehicle icons (I just don't have the time for that much art-stuff anymore).  Originally I wanted the option in there for performance reasons, I just haven't been able to maintain the art-side of things as well as I would like.

**Comment by keenerb** [comment]
Well I logged the issue because I was troubleshooting a crash bug when using inventory tweaks to sort a chest containing your vehicle 3d models.

Using IT with AW and sorting a chest causes the client to jus freeze, apparantly.

**Comment by shadowmage45** [comment]
No worries -- its good to report the issues either way.

As to inventory tweaks...that is strange...did it work after changing to the 2d icons, or still hangs?
