### ISSUE TITLE
Rendering order or texture bug - Research book - Crafting tab

### ISSUE THREAD

**Issue by TechStack** [shadowmage45/AncientWarfare#32]
Open the research book.
Select the Crafting tab.
Scroll down to the Vehicle Engineering station.

In the screenshot below the chest top is rendered before the chest bottom making it hard to tell what item it is:
http://i.imgur.com/D28s9s0.png 

Also in the Civic crafting table this can occur when hovering over a tool / weapon with the damage / attack value debug info on.
http://i.imgur.com/eOU4geX.png

This is a lesser bug because only some players will have that feature activated ( F3 +H )

This was in .035 or .034 i have not checked the latest .036 yet.

**Comment by shadowmage45** [comment]
both are caused by draw-order issues.  The first one is actually a new one, probably introduced when I cleaned up/optimized the gui render code -- I had was previously push/pulling the entire attrib stack between rendering each GUI element -- which while it caught/fixed every potential error caused by any gui element, was extremely slow.

The first issue, I have fixed, and should have the update available with the next release.

The second one is a bit trickier to fix...but I should have a solution available with the next release as well.
