### ISSUE TITLE
Scanning of surtain blocks wount rotate.

### ISSUE THREAD

**Issue by Lazsa** [shadowmage45/AncientWarfare#62]
Nether brick stairs and trapdoors wount rotate when u try to build them from the drafting table.
That if u try to build them in a different angle that u previously svanned them from.

ANyway could u check if there are more Blocks that wount rotate aswell ?

ALso Important! : The special reinforced Blocks and prb all Your included ancient warfare mod
Blocks will not be needed as materials if u scan them in. This is a way to duplicate the special
Blocks big time. Just have like 20 reinforced stones and scan them in then build it from drafting table
and do this alot and u end up with infinite reinforced stone.

Hope this will be fixed aswell

Lazsa

**Comment by shadowmage45** [comment]
Thanks for the report.

Is this using the latest test version?  Some of those problems should have been fixed in the latest releases. (mostly block rotation stuff)

As far as the survival mode/drafting station -- yep, that is the intended behavior.  There will be no templates included by default for survival mode.  They are something players will need to scan / setup / verify themselves.  So, if a template allows 'cheating', it is entirely up to the server admins if they want to allow or disallow that template.  While I can add the recipe support for -my- blocks (which fixes the problem with reinforced blocks), there is no way for me to do that for other mods -- someone will need to write a block-handling plugin if they want those mods to be properly and fully supported.

I'll look into adding support for the 'reinforced blocks' -- but I'm a bit hesitant, as I already know that those blocks will be no longer present in the 1.7 versions

**Comment by shadowmage45** [comment]
I have fixed the reinforced blocks not having a resource list in the drafting station.  This should also add resources for any other mod-added blocks -- but it is a generic method, and will probably not work for all mod-added blocks (some of them will be unobtainable blocks that have an item equivalent).

However, that is as good as I can do it without writing a custom plugin for the mod(s) involved.

I'll take a further look at the block-rotation stuff shortly.

**Comment by shadowmage45** [comment]
I've added support for rotation of trapdoors via the template scan/build system.  This should be available with the next test-release.

Any other specific blocks that I need to take a look at?  (I don't really have time to go through the entire block-list, but will certainly examine any that you find as not working)

**Comment by Lazsa** [comment]
ty for Your fast reply, i will take a look into it b4 weekend begins.

Lazsa
