### ISSUE TITLE
NPC AI tracking system.

### ISSUE THREAD

**Issue by Lazsa** [shadowmage45/AncientWarfare#63]
Hey

I been busy building alot lately and when i set up the npc's to work in them they seem to get stuck alot.
I find myself kind of rebuilding my builds to get the npc's unstuck. 
ANyway doing this alot i found out that it seems they get stuck more often on the Blocks that are not considered solid. Like fences, glass, halfslabs etc. Is there away to improve the tracking system to
deal with this ?

Lazsa

**Comment by shadowmage45** [comment]
For the 1.6.4 releases -- unfortunately not.  The pathfinding code is quite a mess -- every time I try and 'fix' that issue, it causes 4-5 others.  And I've tried to fix it many times...each time I'll get a specific block or two fixed, and it breaks many others (and yes, it is all the 'special' blocks....solid blocks were easy to deal with).

For 1.7 + -- I will be returning to use the vanilla pathfinder (instead of the custom one I have in 1.6), which, while it might not fix those problems, means they are Mojangs problems :)

Thanks for the report.  I am closing this for now as there is nothing that I can really do about it at this point in time (without rewriting the entire NPC system -- which I really don't have time to do).

If the issue persists in the 1.7 releases, please open an issue for those releases.
